spring: 
  application: 
      name: simulate-login-microservice   

#数据库配置
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3316/lg_user?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT user()
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
   #配置Redis
   # Redis Config
  redis:
   host: localhost
   port: 6379
   # 连接超时时间 单位 ms（毫秒）
   timeout: 3000
    #连接池中的最大空闲连接，默认值也是8。
   pool:
     max-idle: 8
#连接池中的最小空闲连接，默认值也是0。
     min-idle: 0
# 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
     max-active: 8
# 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
     max-wait: 1
     
     
  #日志配置
logging:
    config: classpath:log4j2.xml

    



  